version: '2'
services:
  jirapokerbackend:
      build: .
      ports:
        - "5001:5000"
      environment:
        - MONGO_DB_NAME=jirapoker
        - MONGO_HOST_NAME=mongodb
        - JIRA_USER=
        - JIRA_TOKEN=
      container_name: jirapokerbackend
      depends_on:
        - mongodb
      networks:
        - frontend
        - backend

  mongodb:
    image: mongo:4.0.8
    ports:
      - "27017:27017"
    container_name: mongodb
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=jirapoker
      - MONGODB_DATA_DIR=/data/db
      - MONDODB_LOG_DIR=/dev/null
    volumes:
      - ./mongodbdata:/data/db
    networks:
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
